export type ErrorCode =
  | "VALIDATION_ERROR"
  | "TRIP_REQUEST_NOT_FOUND"
  | "TRIP_REQUEST_ALREADY_CANCELED"
  | "HOLIDAY_TRIP_NOT_ALLOWED"
  | "HOLIDAYS_API_UNAVAILABLE"
  | "INTERNAL_SERVER_ERROR";

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  TRIP_REQUEST_NOT_FOUND: 404,
  TRIP_REQUEST_ALREADY_CANCELED: 409,
  HOLIDAY_TRIP_NOT_ALLOWED: 409,
  HOLIDAYS_API_UNAVAILABLE: 502,
  INTERNAL_SERVER_ERROR: 500,
};
